In [1]:
from __future__ import print_function
import torch


In [2]:
x=torch.empty(5,3)
print(x)

tensor([[8.9082e-39, 1.0194e-38, 9.1837e-39],
        [8.4490e-39, 9.6429e-39, 8.4490e-39],
        [9.6429e-39, 9.2755e-39, 1.0286e-38],
        [9.0919e-39, 8.9082e-39, 9.2755e-39],
        [8.4490e-39, 1.0194e-38, 9.0919e-39]])


In [3]:
x=torch.rand(5,3)
print(x)

tensor([[0.7679, 0.4636, 0.8440],
        [0.8042, 0.2962, 0.6089],
        [0.3824, 0.0390, 0.3064],
        [0.4736, 0.7234, 0.2992],
        [0.3138, 0.0726, 0.9289]])


In [4]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 重载 dtype!
print(x)                                      # 结果size一致

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.5399,  1.2768, -0.4510],
        [-0.3023,  0.1751,  0.7314],
        [-0.3228, -0.2144, -0.6533],
        [ 1.5477, -0.7869, -0.8342],
        [-0.2525, -0.2363, -0.3173]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.3364,  2.1543,  0.1896],
        [ 0.0947,  0.7132,  1.5903],
        [ 0.4604,  0.4703, -0.2381],
        [ 2.0653, -0.1144, -0.6709],
        [ 0.0644,  0.1036,  0.5172]])


In [9]:
print(torch.add(x, y))


tensor([[-0.3364,  2.1543,  0.1896],
        [ 0.0947,  0.7132,  1.5903],
        [ 0.4604,  0.4703, -0.2381],
        [ 2.0653, -0.1144, -0.6709],
        [ 0.0644,  0.1036,  0.5172]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.3364,  2.1543,  0.1896],
        [ 0.0947,  0.7132,  1.5903],
        [ 0.4604,  0.4703, -0.2381],
        [ 2.0653, -0.1144, -0.6709],
        [ 0.0644,  0.1036,  0.5172]])


In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.3364,  2.1543,  0.1896],
        [ 0.0947,  0.7132,  1.5903],
        [ 0.4604,  0.4703, -0.2381],
        [ 2.0653, -0.1144, -0.6709],
        [ 0.0644,  0.1036,  0.5172]])


In [12]:
print(x[:, 1])


tensor([ 1.2768,  0.1751, -0.2144, -0.7869, -0.2363])


In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2942])
-0.294170618057251


In [15]:
#将torch的Tensor转化为NumPy数组
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [18]:
#将NumPy数组转化为Torch张量
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [19]:
# 当GPU可用时,我们可以运行以下代码
# 我们将使用`torch.device`来将tensor移入和移出GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # 直接在GPU上创建tensor
    x = x.to(device)                       # 或者使用`.to("cuda")`方法
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # `.to`也能在移动时改变dtype

In [2]:
torch.cuda.is_available()

True

In [3]:
t=torch.tensor([1,2,3])
t


tensor([1, 2, 3])

In [4]:
t=t.cuda()
t

tensor([1, 2, 3], device='cuda:0')