In [1]:
from numpy import *

In [3]:
random.rand(4,4)

array([[0.79664991, 0.70055291, 0.23504084, 0.05845698],
       [0.66756728, 0.72702487, 0.18783168, 0.9699685 ],
       [0.10892547, 0.21417347, 0.40414893, 0.25512412],
       [0.13637076, 0.89731678, 0.99893648, 0.0860762 ]])

In [2]:
# create a 4*4 random array

In [4]:
# transform array to matrix
randMat=mat(random.rand(4,4))

In [5]:
randMat

matrix([[0.11785405, 0.430492  , 0.32414314, 0.40494717],
        [0.96407491, 0.74797956, 0.9142055 , 0.20396316],
        [0.89034087, 0.78476237, 0.88696818, 0.99569746],
        [0.02017958, 0.11405403, 0.36486983, 0.66728525]])

In [6]:
invRandMat=randMat.I
invRandMat #matrix 求逆运算

matrix([[-2.43976899, -0.59383269,  2.12326469, -1.50615006],
        [ 3.55005097, -0.5112632 ,  0.13348647, -2.19728579],
        [-0.24235442,  2.40871785, -2.65246915,  3.368736  ],
        [-0.40048282, -1.211736  ,  1.36333706,  0.07770687]])

In [7]:
myEye=randMat*invRandMat
myEye-eye(4)

matrix([[-4.44089210e-16,  0.00000000e+00, -1.11022302e-16,
          3.46944695e-17],
        [-1.38777878e-16,  0.00000000e+00,  5.55111512e-17,
          2.42861287e-17],
        [-5.55111512e-16,  2.22044605e-16,  2.22044605e-16,
         -2.63677968e-16],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         -2.22044605e-16]])

In [8]:
myEye

matrix([[ 1.00000000e+00,  0.00000000e+00, -1.11022302e-16,
          3.46944695e-17],
        [-1.38777878e-16,  1.00000000e+00,  5.55111512e-17,
          2.42861287e-17],
        [-5.55111512e-16,  2.22044605e-16,  1.00000000e+00,
         -2.63677968e-16],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]])

In [9]:
eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])